# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import threading
import time

from PyQt5 import QtCore, QtGui, QtWidgets

from Misc import fetchAppIcon
from ThreadWorker import ThreadWorker
from Observable import Observable
from Protocol import PROTOCOLS
from PyQt5.Qt import Qt
import MainChatScreen

# noinspection PyUnresolvedReferences
import StyleSheets.login_screen_css


class LoginScreen(Observable):
    def __init__(self, ClientTCP):
        Observable.__init__(self)
        self.client = ClientTCP
        self.client.attach(self)
        self.thread_worker = ThreadWorker()

    def setupUi(self, LoginWindow):
        self.main_window = LoginWindow
        threading.Thread(target=self.client.recv_msg, daemon=True).start()
        self.thread_worker.finished.connect(self.loadMainChatWindow)
        self.thread_worker.start()

        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.setFixedSize(678, 582)
        LoginWindow.setWindowIcon(fetchAppIcon())
        LoginWindow.setMinimumSize(QtCore.QSize(678, 582))
        LoginWindow.setMaximumSize(QtCore.QSize(678, 582))
        LoginWindow.setWindowOpacity(1.0)
        LoginWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_white_label = QtWidgets.QLabel(self.centralwidget)
        self.login_white_label.setGeometry(QtCore.QRect(10, 10, 331, 531))
        self.login_white_label.setMinimumSize(QtCore.QSize(0, 0))
        self.login_white_label.setAutoFillBackground(False)
        self.login_white_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                             "")
        self.login_white_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_white_label.setLineWidth(0)
        self.login_white_label.setText("")
        self.login_white_label.setObjectName("login_white_label")
        self.login_logo_label = QtWidgets.QLabel(self.centralwidget)
        self.login_logo_label.setGeometry(QtCore.QRect(340, 10, 335, 531))
        self.login_logo_label.setMinimumSize(QtCore.QSize(0, 0))
        self.login_logo_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.login_logo_label.setAutoFillBackground(False)
        self.login_logo_label.setStyleSheet("image: url(:/window_logo/login_logo.jpg);\n"
                                            "background-color: rgb(255, 255, 255);")
        self.login_logo_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_logo_label.setLineWidth(0)
        self.login_logo_label.setText("")
        self.login_logo_label.setObjectName("login_logo_label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 20, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.username_textfield = QtWidgets.QLineEdit(self.centralwidget)
        self.username_textfield.setGeometry(QtCore.QRect(90, 110, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.username_textfield.setFont(font)
        self.username_textfield.setMaxLength(100)
        self.username_textfield.setFrame(False)
        self.username_textfield.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_textfield.setClearButtonEnabled(True)
        self.username_textfield.setObjectName("username_textfield")
        self.password_textfield = QtWidgets.QLineEdit(self.centralwidget)
        self.password_textfield.setGeometry(QtCore.QRect(90, 170, 231, 31))
        self.password_textfield.setFrame(False)
        self.password_textfield.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password_textfield.setClearButtonEnabled(True)
        self.password_textfield.setObjectName("password_textfield")
        self.password_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.password_icon_label.setGeometry(QtCore.QRect(30, 160, 61, 41))
        self.password_icon_label.setStyleSheet("image: url(:/password_icon/password_icon1.png);")
        self.password_icon_label.setText("")
        self.password_icon_label.setObjectName("password_icon_label")
        self.username_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.username_icon_label.setGeometry(QtCore.QRect(40, 100, 51, 41))
        self.username_icon_label.setStyleSheet("image: url(:/username_icon/username_icon1.png);")
        self.username_icon_label.setText("")
        self.username_icon_label.setObjectName("username_icon_label")
        self.username_line = QtWidgets.QFrame(self.centralwidget)
        self.username_line.setEnabled(True)
        self.username_line.setGeometry(QtCore.QRect(90, 130, 231, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.username_line.setFont(font)
        self.username_line.setLineWidth(1)
        self.username_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.username_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.username_line.setObjectName("username_line")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(70, 250, 111, 41))
        self.login_button.setStyleSheet("QPushButton{\n"
                                        "    color: white;\n"
                                        "    background-color: rgb(58, 134, 255);\n"
                                        "    border-radius: 20px;\n"
                                        "}")
        self.login_button.setObjectName("login_button")
        self.forgot_password_link_button = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.forgot_password_link_button.setGeometry(QtCore.QRect(80, 320, 201, 41))
        self.forgot_password_link_button.setObjectName("forgot_password_link_button")
        self.google_logo_label = QtWidgets.QLabel(self.centralwidget)
        self.google_logo_label.setGeometry(QtCore.QRect(20, 470, 71, 51))
        self.google_logo_label.setStyleSheet("image: url(:/fast_login_icons/google_login_logo.png);")
        self.google_logo_label.setText("")
        self.google_logo_label.setObjectName("google_logo_label")
        self.facebook_logo_label = QtWidgets.QLabel(self.centralwidget)
        self.facebook_logo_label.setGeometry(QtCore.QRect(90, 470, 71, 51))
        self.facebook_logo_label.setStyleSheet("image: url(:/fast_login_icons/facebook_login_logo.png);")
        self.facebook_logo_label.setText("")
        self.facebook_logo_label.setObjectName("facebook_logo_label")
        self.linkedin_logo_label = QtWidgets.QLabel(self.centralwidget)
        self.linkedin_logo_label.setGeometry(QtCore.QRect(160, 470, 71, 51))
        self.linkedin_logo_label.setStyleSheet("image: url(:/fast_login_icons/linkedin_login_logo.png);")
        self.linkedin_logo_label.setText("")
        self.linkedin_logo_label.setObjectName("linkedin_logo_label")
        self.twitter_logo_label = QtWidgets.QLabel(self.centralwidget)
        self.twitter_logo_label.setGeometry(QtCore.QRect(230, 470, 71, 51))
        self.twitter_logo_label.setStyleSheet("image: url(:/fast_login_icons/twitter_login_logo.png);")
        self.twitter_logo_label.setText("")
        self.twitter_logo_label.setObjectName("twitter_logo_label")
        self.signin_label = QtWidgets.QLabel(self.centralwidget)
        self.signin_label.setGeometry(QtCore.QRect(30, 430, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.signin_label.setFont(font)
        self.signin_label.setObjectName("signin_label")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(190, 250, 111, 41))
        self.cancel_button.setStyleSheet("QPushButton{\n"
                                         "    color: white;\n"
                                         "    background-color: rgb(236, 31, 39);\n"
                                         "    border-radius: 20px;\n"
                                         "}")
        self.cancel_button.setObjectName("cancel_button")
        self.password_line = QtWidgets.QFrame(self.centralwidget)
        self.password_line.setEnabled(True)
        self.password_line.setGeometry(QtCore.QRect(90, 190, 231, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.password_line.setFont(font)
        self.password_line.setLineWidth(1)
        self.password_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.password_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.password_line.setObjectName("password_line")
        self.login_result = QtWidgets.QLabel(self.centralwidget)
        self.login_result.setGeometry(QtCore.QRect(90, 210, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.login_result.setFont(font)
        self.login_result.setObjectName("login_result")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(330, 11, 20, 527))
        self.line.setMinimumSize(QtCore.QSize(0, 527))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.line.setFont(font)
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.login_white_label.raise_()
        self.label_3.raise_()
        self.username_textfield.raise_()
        self.password_textfield.raise_()
        self.password_icon_label.raise_()
        self.username_icon_label.raise_()
        self.login_button.raise_()
        self.forgot_password_link_button.raise_()
        self.google_logo_label.raise_()
        self.facebook_logo_label.raise_()
        self.linkedin_logo_label.raise_()
        self.twitter_logo_label.raise_()
        self.signin_label.raise_()
        self.cancel_button.raise_()
        self.username_line.raise_()
        self.password_line.raise_()
        self.login_result.raise_()
        self.login_logo_label.raise_()
        self.line.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 21))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

        # Manual components settings
        LoginWindow.keyPressEvent = self.keyPressEvent
        self.username_textfield.mousePressEvent = self.mousePressEvent
        self.password_textfield.mousePressEvent = self.mousePressEvent
        self.login_button.clicked.connect(self.login)
        self.cancel_button.clicked.connect(exit)

        self.username_textfield.setText("Extarminator")
        self.password_textfield.setText("1")

    def retranslateUi(self, login_screen):
        _translate = QtCore.QCoreApplication.translate
        login_screen.setWindowTitle(_translate("Welcome to PyChat", "Welcome to PyChat"))
        self.label_3.setText(_translate("MainWindow", "Login Zone"))
        self.username_textfield.setText(_translate("MainWindow", "Your Username..."))
        self.password_textfield.setText(_translate("MainWindow", "password"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.forgot_password_link_button.setText(_translate("MainWindow", "Forgot Your Password?"))
        self.signin_label.setText(_translate("MainWindow", "Sign In With:"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))

    def keyPressEvent(self, event):
        if event.key() == Qt.Key_Return and self.username_textfield.hasFocus() is True:
            self.login_button.click()

        if event.key() == Qt.Key_Return and self.password_textfield.hasFocus() is True:
            self.login_button.click()

        if event.key() == Qt.Key_Enter and self.username_textfield.hasFocus() is True:
            self.login_button.click()

        if event.key() == Qt.Key_Enter and self.password_textfield.hasFocus() is True:
            self.login_button.click()

        if event.key() == Qt.Key_Escape:
            exit(0)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton and self.username_textfield.hasFocus() is True:
            self.username_textfield.setText("")

        if event.button() == Qt.LeftButton and self.password_textfield.hasFocus() is True:
            self.password_textfield.setText("")

    def login(self):
        cmd = PROTOCOLS["login_request"]
        username = self.username_textfield.text()
        password = self.password_textfield.text()
        self.client.send_msg(cmd, username + "#" + password)

    # noinspection PyUnresolvedReferences
    def update(self, notif, data):
        if notif == "LOGIN_ERROR":
            self.login_result.setText("Invalid username or password.")
            self.login_result.setStyleSheet("color: rgb(236, 31, 39);")
            time.sleep(0.5)
            self.login_result.setText(" ")

        if notif == "LOGIN_OK":
            # notification to BOT
            self.client.send_msg(PROTOCOLS["bot_user_logged_in"], self.username_textfield.text())

            # Send beacon to load the MainChatScreen
            self.thread_worker.finished.emit(100)

    def loadMainChatWindow(self):
        self.thread_worker.terminate()
        self.main_window.close()
        self.client.detach(self)
        MainChatScreen.run(ClientTCP=self.client)

def run(ClientTCP):
    window = QtWidgets.QMainWindow()
    LSF = LoginScreen(ClientTCP=ClientTCP)
    LSF.setupUi(window)
    window.show()
